#!/bin/bash
###################################################################################
## this file will install the dependencies for python and opencv
###################################################################################

apt-get update 
# Requirement for ope
apt-get install -y libgtk2.0-dev 
#apt-get install -y cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
#apt-get install -y libgtk2.0-dev zlib1g-dev libjpeg-dev libwebp-dev libpng-dev libtiff5-dev libjasper-dev libopenexr-dev libgdal-dev
# Media I/O:
#apt-get install -y libdc1394-22-dev libavcodec-dev libavformat-dev libswscale-dev libtheora-dev libvorbis-dev libxvidcore-dev libx264-dev yasm libopencore-amrnb-dev libopencore-amrwb-dev libv4l-dev libxine2-dev
# ffmpeg
#apt-get install -y ffmpeg libav-tools x264 x265
# Parallelism and linear algebra libraries:
#apt-get install -y libtbb-dev libeigen3-dev
#install c++ lib
#apt-get install -y libboost-all-dev
# Python:
apt-get install -y python3-pip python3-dev python3-tk #python3-numpy #python3-setuptools
#pip3 install opencv-python
# Documentation:
#apt-get install -y doxygen
# other
#apt-get install -y wget unzip 
    

